CREATE TABLE "GCG_4898_Invoice_DTL"(
 "TERMINAL_NO" CHAR(3),
 "RPTID" CHAR(6),
 "KEY_SEQ" CHAR(6),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "PRICE_5" NUMERIC(12,5),
 "NET_AMT" NUMERIC(10,2),
 "QTY_ORDER" NUMERIC(9,0),
 "QTY_BO" NUMERIC(9,0),
 "QTY_SHIPPED" NUMERIC(9,0),
 "ORDER_NO" LONGVARCHAR,
 "Key_Group" CHAR(6));
